services:

  opensearch:
    image: opensearchproject/opensearch:2.14.0
    environment:
      discovery.type: single-node
      plugins.security.disabled: true # disable https and logins
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: Str0ng@Passw0rd!
      compatibility.override_main_response_version: true
      bootstrap.memory_lock: true # lock JVM heap memory on RAM
#      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1 # unlimited
        hard: -1
    ports:
      - "9200:9200"
      - "9600:9600" # required for Performance Analyzer
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.14.0
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
    depends_on:
      - opensearch
    networks:
      - opensearch-net

networks:
  opensearch-net:
